# Generated by Django 5.0.6 on 2024-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
