# Generated by Django 5.0.6 on 2024-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_airplane_name_alter_airplanetype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(
                help_text="Airplane name (like 'Boeing 747')",
                max_length=128,
                unique=True,
            ),
        ),
    ]
