# Generated by Django 5.0.6 on 2024-07-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_crew"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Airport code (like 'JFK')", max_length=3, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Airport name", max_length=64, unique=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=64, null=True)),
                ("state", models.CharField(blank=True, max_length=64, null=True)),
                ("country", models.CharField(max_length=64)),
            ],
        ),
    ]
