# Generated by Django 5.0.6 on 2024-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_airport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(help_text="Airport name", max_length=64),
        ),
    ]
