# Generated by Django 5.0.6 on 2024-07-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_airport_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="lat",
            field=models.FloatField(
                blank=True, help_text="Longitude in degrees (format: 30.752)", null=True
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="lon",
            field=models.FloatField(
                blank=True, help_text="Latitude in degrees (format: 30.752)", null=True
            ),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination",
                        to="app.airport",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="app.airport",
                    ),
                ),
            ],
        ),
    ]
