# Generated by Django 5.0.6 on 2024-07-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_route_distance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="distance",
        ),
    ]
